### ISSUE TITLE
Doesn't work for me with version 11.6.2 (397016)

### ISSUE THREAD

**Issue by borisyurkevich** [aidaan/bbedit-swift-language-module#2]
I've moved the file and restarted BBEdit, it doesn't appear in the list.

![screen shot 2016-10-20 at 12 14 38](https://cloud.githubusercontent.com/assets/1362354/19557692/d20f09c8-96be-11e6-98a3-eb0ace2e6f3f.png)

<img width="203" alt="screen shot 2016-10-20 at 12 15 13" src="https://cloud.githubusercontent.com/assets/1362354/19557700/de412528-96be-11e6-851d-0476ec6ab703.png">

<img width="506" alt="screen shot 2016-10-20 at 12 15 11" src="https://cloud.githubusercontent.com/assets/1362354/19557699/de408712-96be-11e6-9d18-08bce1970194.png">

**Comment by sigpoggy** [comment]
Me too

**Comment by borisyurkevich** [comment]
@sigpoggy try this one https://github.com/curtclifton/bbedit-swift-clm

**Comment by sigpoggy** [comment]
Thanks...

**Comment by bbezanson** [comment]
See #3 and issue #4. I fixed that and things seem to work fine in BBEdit 11.6.3.
